baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
title = "Waaprint Blog"
[[menu.footer]]
URL = "faq"
name = "F.A.Q"
url = "https://waaprint.com/faq"
weight = 3
[[menu.footer]]
URL = "about"
name = "About Us"
url = "https://waaprint.com/about"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact us"
weight = 1
[[menu.main]]
URL = "faq"
name = "F.A.Q"
url = "https://waaprint.com/faq"
weight = 3
[[menu.main]]
URL = "about"
name = "About us"
url = "https://waaprint.com/about"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Adams Paul"
contact_form_action = "#"
copyright = "&copy; 2020 [Waaprint](https://waaprint.com) All Rights Reserved"
description = "Waaprint.com blog, the #1 On demand printing platform."
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/wb.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Waaprint Blog. <br> Stay ahead, Stay updated!"
[params.cta]
description = "www.waaprint.com, the #1 On demand printing platform in Africa."
enable = true
image = "images/main.png"
title = "Get the best printing deals!"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://waaprint.com/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = false
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "https://www.fb.com/waaprint1"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/Waaprint1"
[[params.social]]
icon = "ti-instagram"
link = "https://instagram.com/waaprint1"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/waaprint"
